### ISSUE TITLE
Composer install not work

### ISSUE THREAD

**Issue by ignatenkovnikita** [miknatr/fias#3]
Hello
How install depends

after composer install 
get error

`[RuntimeException]                                                                                                
  Failed to execute git clone --no-checkout 'git@bitbucket.org:miknatr/tos-kola.git' '/var/www/address/vendor/stiffbeards/kola' && cd '/var/www/address/vendor/stiffbeards/kola' && git remote add composer 'git@bitbucket.org:miknatr/tos-kola.git' && git fetch composer                                        
  Permission denied (publickey).                                                                                    
  fatal: Could not read from remote repository.                                                                     
  Please make sure you have the correct access rights                                                               
  and the repository exists.   `

**Comment by LivesInSpb** [comment]
@ignatenkovnikita 
#4 now it's work right.

**Now, this issue can be closed.**
